runtime: python38
instance_class: F4_1G
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker xpl.rest.backend.endpoints.main:client_api
#entrypoint: uvicorn main:client_api
env_variables:
  XPL_ENV: "DEV"
  XPL_CODE_DIR: "~/"
  XPL_HOST: "xpl.rest.backend"
service: client-api-dev